# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalculatorExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CalculatorExample
  pod 'HPCalculator', :path => '../HPCalculator'

end

target 'HPCalculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HPCalculator

  target 'HPCalculatorTests' do
    # Pods for testing
  end

end
